import WalletHeader from "@/components/wallet/WalletHeader";
import WalletWrapper from "@/components/wallet/WalletWrapper";
import { validateRequest } from "@/lib/auth";
import { User } from "@/types";
import { Metadata } from "next";
import { redirect } from "next/navigation";
import React from "react";

export const metadata: Metadata = {
  title: "Wallpay | Wallet",
  description: "Generated by create next app",
};

export default async function UserWalletPage() {
  const { isAuthenticated, isUserAuthenticated, userCookie } =
    await validateRequest();

  if (!isUserAuthenticated || !isAuthenticated) {
    redirect("/auth/signin");
  }

  let user: User;
  try {
    user = JSON.parse(userCookie!.value) as User;
  } catch (error) {
    console.error("Error parsing user cookie:", error);
    redirect("/auth/signin");
  }

  return (
    <div className="flex flex-col gap-y-4 relative">
      <WalletHeader user={user} />
      <WalletWrapper user={user} />
    </div>
  );
}
