import WalletHeader from "@/components/wallet/WalletHeader";
import WalletWrapper from "@/components/wallet/WalletWrapper";
import { User } from "@/types";
import { Metadata } from "next";
import { cookies } from "next/headers";
import { redirect } from "next/navigation";
import React from "react";

export const metadata: Metadata = {
  title: "Wallpay | Wallet",
  description: "Generated by create next app",
};

export default async function UserWalletPage() {
  const cookieStore = await cookies();
  const userCookie = cookieStore.get("user");
  const authenticatedCookie = cookieStore.get("authenticated");

  const isUserAuthenticated =
    userCookie && userCookie.value && userCookie.value !== "null";
  const isAuthenticated =
    authenticatedCookie &&
    authenticatedCookie.value &&
    authenticatedCookie.value !== "null";

  if (!isUserAuthenticated || !isAuthenticated) {
    redirect("/auth/signin");
  }

  let user: User;
  try {
    user = JSON.parse(userCookie!.value) as User;
  } catch (error) {
    console.error("Error parsing user cookie:", error);
    redirect("/auth/signin");
  }

  return (
    <div className="flex flex-col gap-y-4 relative">
        <WalletHeader user={user} />
        <WalletWrapper user={user} />
    </div>
  );
}
