import { Metadata } from 'next';
import React from 'react'

export const metadata: Metadata = {
  title: "Wallpay | Wallet",
  description: "Generated by create next app",
};

export default function UserWalletPage() {
  return (
    <div>UserWalletPage</div>
  )
}
