import { ModeToggle } from "@/components/global/mode-toggle";
import { Metadata } from "next";
import Link from "next/link";
import React from "react";

export const metadata: Metadata = {
  title: "Wallpay | Signin",
  description: "Generated by create next app",
};

export default function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="bg-background flex min-h-svh flex-col items-center p-6 md:p-10">
      { children }
      <footer className="footer mx-auto flex w-full max-w-[87.5rem] flex-col items-center p-3 sm:flex-row sm:justify-between">
        <p className="flex items-center">
          <span className="block">Made with 💚 |</span>
          <Link
            href="https://x.com/codewithmontana"
            target="_blank"
            className="font-semibold ml-1 flex items-center gap-x-1 hover:underline"
          >
            Repo
          </Link>
          .
        </p>
        <ModeToggle />
      </footer>
    </div>
  );
}
